// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.LayoutManager = (function(_super) {
    __extends(LayoutManager, _super);

    function LayoutManager() {
      _ref = LayoutManager.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    LayoutManager.prototype.className = "layout-manager";

    LayoutManager.prototype.initialize = function() {
      return this.regionEls = {};
    };

    LayoutManager.prototype.template = (function() {
      var t;

      return t = '\
    <div class="region navigation"></div>\
    <div class="region content"></div>\
    ';
    })();

    LayoutManager.prototype.render = function() {
      this.$el.append(this.template);
      this.regionEls = {
        "navigation": this.$el.find(".region.navigation"),
        "content": this.$el.find(".region.content")
      };
      this.regionEls.navigation.append(new window.SidebarView().render().$el);
      this.showHome();
      return this;
    };

    LayoutManager.prototype.swapContentView = function(ViewConstructor) {
      var _ref1;

      if ((_ref1 = this.activeContentView) != null) {
        _ref1.remove();
      }
      this.activeContentView = new ViewConstructor();
      return this.regionEls.content.append(this.activeContentView.render().$el);
    };

    LayoutManager.prototype.showContacts = function() {
      return this.swapContentView(window.ContactsView);
    };

    LayoutManager.prototype.showProfile = function() {
      return this.swapContentView(window.ProfileView);
    };

    LayoutManager.prototype.showHome = function() {
      return this.swapContentView(window.HomePageView);
    };

    return LayoutManager;

  })(Backbone.View);

}).call(this);
